# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Code monkey Nest
subtitle: ""
description: ""
keywords:
author: 巷子里的老张先生
language: zh-CN
timezone: ""
navbar:
  blog_title: 巷子里的老张先生
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - {
        key: "tag",
        link: "/tags/",
        name: "标签",
        icon: "iconfont icon-tags-fill",
      }
    - {
        key: "archives",
        link: "/archives/",
        name: "武林秘籍",
        icon: "iconfont icon-books",
      }
    - {
        key: "journey",
        link: "/journey/",
        name: "吃喝玩乐",
        icon: "iconfont icon-plays-fill",
      }
    - {
        key: "about",
        link: "/about/",
        icon: "iconfont icon-user-fill",
        name: "联系我",
      }
# 统计
footer:
  statistics:
    enable: true
    source: "busuanzi" # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次" # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# 首页配置
index:
  banner_img: https://cdn.houdemingxin.com/image/default/27210CC0731046F0978671A017530FC1-6-2.png
  # 打字机

  slogan:
    enable: true
    text: 路漫漫其修远兮，吾将上下而求索
    api:
      enable: true
      url: "https://v1.hitokoto.cn/"
      loop: true
      speed: 100
      method: "GET"
      headers: {}
      keys: ["hitokoto"]

  # 文章摘要
  auto_excerpt:
    enable: false
  post_meta:
    date: true
    categories: true
    comments: true
    category: true
    tag: true

# 文章页配置
post:
  comments:
    enable: true
    type: disqus
  disqus:
  shortname: fluid
code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"
    highlightjs:
      style: "Github Gist"
      bg_color: false
    prismjs:
      style: "default"
      preprocess: true

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid
# 暗色模式
dark_mode:
  enable: true
  default: auto
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/laozhangxiansheng/laozhangxiansheng.github.io
  branch: master
# 标签页
tag:
  banner_img: https://cdn.houdemingxin.com/image/default/8FD662F5172648958B023FC0D9E657AF-6-2.png
  categories:
    - 浏览器
    - 编程语言
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px # 字号单位
    start_color: "#BBBBEE"
    end_color: "#337ab7"
# 归档页
archive:
  banner_img: https://cdn.houdemingxin.com/image/default/07909BF5A26F44CD9D0A1600BD5DE827-6-2.png

# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true #开关插件版看板娘
  scriptFrom: local # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://npm.elemecdn.com/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    use: live2d-widget-model-koharu # npm-module package name
    # use: wanko # 博客根目录/live2d_models/ 下的目录名
    # use: ./wives/wanko # 相对于博客根目录的路径
    # use: https://npm.elemecdn.com/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
  display:
    position: left #控制看板娘位置
    width: 50 #控制看板娘大小
    height: 100 #控制看板娘大小
  mobile:
    show: false # 手机中是否展示
